# PostgreSQL Configuration (Production)
spring.datasource.url=${URL_DB}           # Aquí Render inyectará la URI de Supabase
spring.datasource.username=${USERNAME_DB} # Usuario de la DB
spring.datasource.password=${PASSWORD_DB} # Contraseña de la DB

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update      # Puede ser update o validate según tu necesidad
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SendGrid Configuration (igual si lo usas)
sendgrid.api.key=${SENDGRID_API_KEY}

# Server Configuration
server.port=8080