# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/marea_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# SendGrid Configuration
sendgrid.api.key=${SENDGRID_API_KEY}

# Server Configuration
server.port=8080

#asdasd